# There's absolutely no reason to use a makefile here. If this is on the github repo it's because I forgot to remove it. 
# I wasn't doing this in Rstudio so just being able to type make to run the script was useful - that's what this exists.

run:
	R -f app.R
